# George Bool

[George Boole](https://en.wikipedia.org/wiki/George_Boole) (/buːl/; 1815 – 1864) was a largely self-taught English mathematician, philosopher, and logician, most of whose short career was spent as the first professor of mathematics at Queen's College, Cork in Ireland.

In [ ]:
# write a True boolean value as text

# write a False boolean value as text

## The `bool()` function

`False` can also be notated as `0`, and `True` can be represented as `1`. Try converting 0, and 1 to their respective boolean values using the `bool()` function.

In [ ]:
# write a True boolean value as a number using bool()

In [ ]:
# write a False boolean value as a number using bool()

## Using the `type()` function
Verify you are working with boolean values using the `type()` function below.

In [ ]:
# return the data type for bool(1)

In [ ]:
# assign bool(1) to the variable name: a_bool

In [ ]:
# verify that a_bool is a bool data type

## Boolean operations
As you will learn later, bools can be used with various operators to represent the truth value of an expression. For example, 1 < 2 is `True`. The output of conditional expressions is always boolean, or `True` and `False`. Rest assured, we will explore this important topic later in the course.

In [1]:
1 < 2

True

In [ ]:
# == is the equality operator
1 == 0
1 == "1"

In [ ]:
if True:
  print("Execute this line of code")

In [ ]:
if False:
  print("Do nothing")