# Strings

When working with strings, use double quotes to avoid confusion with apostrophes such as `it's` or `that's` which breaks up your code in a way that causes errors.

What's interesting about strings is that you can also use the `+` operator to concatenate strings, or join strings together. For example, `print("Hello, " + "World!")` returns the string `Helo, World!`.

Let's review double quotes, single quotes and the concatination operator:

In [ ]:
# This will causes and error since there are three single quotes
print('This is Jonathan's Macbook')

In [ ]:
# To avoid these syntax errors, you can either use `"` or escape the character

# Double quotes
print("This is Jonathan's Macbook")

# Escaping using the `\` character
print('This is Jonathan\'s Macbook')

# The concatenation operator will concatenate, or join two or more stings. Remember to use spaces!
print("This"  + " is Jonathan's" + " Macbook")

# The takeaway: use double quotes or escape the odd single quotes

## Type conversion

If you want to change a numeric data type such as an `int` or `float` to a string, you might recall that you can use `' '` or `" "` to covert both integers and floats into strings. For example, the variables `my_int` and `my_float` can be converted into strings by enclosing their values with single or double-quotes. Another example, `my_int = "42"` and `my_float = "3.14"`. Be sure to check your work using the `type()` method.

In [ ]:
# "42" is a string, not a number like 42 (without quotes)
my_int = "42"

# check the data type
type(my_int)

In [ ]:
# "3.14" is also a string, not a float like 3.14 (without quotes)
my_float = "3.14"

# check the data type
type(my_float)

In [ ]:
# ask for user input
number = input("Enter a number from 1 - 10: ")

# check the data type
type(number)

In [ ]:
# ask for user input
number = input("Enter a number from 1 - 10: ")

# check the data type
type(int(number))

## String Formatting

The placeholders can include named indexes {price}, numbered indexes {0}, and empty placeholders {}.

In [ ]:
# use string formatting to return the string: John Coltrane practiced 12 hours a day
musician = "{} practiced {} hours a day".format("John Coltrane",12)

In [ ]:
# print musician
print(musician)

In [ ]:
complex_string = "{} is my favorite number and this is a {} statement. My friends know that {} is my {} number.".format(7, True, 7, "lucky")
print(complex_string)
type(complex_string)

7 is my favorite number and this is a True statement. My friends know that 7 is my lucky number.

str

In [ ]:
# try writing the above without the format() method
complex_string = str(7) + " is my favorite number and this is a " + str(True) +  " statement. My friends know that " + str(7) +  " is my lucky number."
print(complex_string)

7 is my favorite number and this is a True statement. My friends know that 7 is my lucky number.

## Advanced Formatting (for DS)

`*` unpacks a list or tuple into position arguments.

`**` unpacks a dictionary into keyword arguments.

In [ ]:
a_list = [12,45,22222,103,6]
print('{0} {2} {1} {2} {3} {2} {4} {2}'.format(*a_list))

12 22222 45 22222 103 22222 6 22222

In [ ]:
a_dict = {'a':12, 'b':45, 'c':22222, 'd':103, 'e':6}
print('{a} {c} {b} {c} {d} {c} {e} {c}'.format(**a_dict))

12 22222 45 22222 103 22222 6 22222